services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: firebase
      POSTGRES_PASSWORD: firebase1
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"